before:
  hooks:
    - go mod download
builds:
-
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - 386
    - amd64
archive:
  replacements:
    darwin: Darwin
    windows: Windows
    linux: Linux
    386: i386
    amd64: x86_64
  # Since GoReleaser will always add the README and LICENSE files to the archive if the file list is empty, you’ll need to provide a filled files on the archive section.
  # A working hack is to use something like this:
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
